baseURL: "https://maplesyrup.sw0rdfish.com"
title: Maple Syrup . sw0rdfish
paginate: 5
theme: PaperMod

params:
  # defaultTheme: light
  # defaultTheme: dark
  defaultTheme: auto # to switch between dark or light according to browser theme

  profileMode:
    enabled: false # needs to be explicitly set

  homeInfoParams:
    Title: maplesyrup . sw0rdfish
    Content: Yadda yadda

  socialIcons: # optional
    - name: "Mastodon"
      url: "https://mastodon.content.town/@maplesyrup"
    - name: "Twitter"
      url: "https://twitter.com/sw0rdfish"